name: deploy-container

on:
  workflow_run:
    workflows: ["build-container"]
    branches: [master]
    types: [completed]
    
permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GH_SECRET}}
        workflow: container-build.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name mfegh2023 -d '$web' -s ./container/latest
    
    - name: Azure logout
      run: |
            az logout
