name: deploy-dodge-table

on:
  push:
    branches:
      - master
    paths:
      - 'packages/dodge-table/**'

defaults:
  run:
    working-directory: packages/dodge-table

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build